name: CI/CD Workflow

on:
  workflow_dispatch:
    inputs:
      testCycleId:
        description: 'The ID of the test cycle'
        required: false
        default: ''
      testCaseKey:
        description: 'The key of the test case'
        required: false
        default: ''

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Print Inputs
        run: |
          echo "Test Cycle ID: ${{ github.event.inputs.testCycleId }}"
          echo "Test Case Key: ${{ github.event.inputs.testCaseKey }}"

      - name: Run Tests
        run: |
          if [ -n "${{ github.event.inputs.testCycleId }}" ]; then
            echo "Running tests with Test Cycle ID: ${{ github.event.inputs.testCycleId }}"
            ./run-tests.sh --testCycleId=${{ github.event.inputs.testCycleId }}
          else
            echo "Test Cycle ID not provided, running default tests"
            ./run-tests.sh
          fi

          if [ -n "${{ github.event.inputs.testCaseKey }}" ]; then
            echo "Running tests with Test Case Key: ${{ github.event.inputs.testCaseKey }}"
            ./run-tests.sh --testCaseKey=${{ github.event.inputs.testCaseKey }}
          else
            echo "Test Case Key not provided, running default tests"
            ./run-tests.sh
          fi
