name: CI/CD Workflow

on:
  workflow_dispatch:
    inputs:
      testCycleId:
        description: 'The ID of the test cycle'
        required: true
        default: ''
      testCaseKey:
        description: 'The key of the test case'
        required: true
        default: ''
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Print Inputs
        run: |
          echo "Test Cycle ID: ${{ github.event.inputs.testCycleId }}"
          echo "Test Case Key: ${{ github.event.inputs.testCaseKey }}"

      - name: Run Tests
        run: |
          ./run-tests.sh --testCycleId=${{ github.event.inputs.testCycleId }} --testCaseKey=${{ github.event.inputs.testCaseKey }}
